; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

declare preserve_mostcc i64 @preserve_most_callee(i64 %x, i64 %y)
declare preserve_mostcc i64 @preserve_most_callee_4args(i64 %x1, i64 %x2, i64 %x3, i64 %x4)

; Test 1: Argument reuse with no spills.
; a (R12) and b (R13) are passed to callee (RDI, RSI) and reused after the call.
; Since R12/R13 are preserved by preserve_most, they should remain in R12/R13 with 0 spills.
define tail_chaincc i64 @tail_chain_caller_reuse(i64 %a, i64 %b) {
; CHECK-LABEL: tail_chain_caller_reuse:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    movq %r13, %rsi
; CHECK-NEXT:    movq %r12, %rdi
; CHECK-NEXT:    callq preserve_most_callee@PLT
; CHECK-NEXT:    addq %r12, %rax
; CHECK-NEXT:    addq %r13, %rax
; CHECK-NEXT:    popq %rcx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq $8
entry:
  %val = call preserve_mostcc i64 @preserve_most_callee(i64 %a, i64 %b)
  %sum1 = add i64 %a, %b
  %res = add i64 %sum1, %val
  ret i64 %res
}

; Test 2: Within budget (total 12 args) with no spills.
; Caller has 8 args, Callee has 4 args.
; a5 (R11) and a8 (RCX) must be moved because they are not preserved or clobbered.
; They should be moved to free preserved registers (R10, RBX) with 0 spills.
define tail_chaincc i64 @tail_chain_caller_budget(
; CHECK-LABEL: tail_chain_caller_budget:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    movq %rcx, %r10
; CHECK-NEXT:    movq %r11, %rbx
; CHECK-NEXT:    movq %r15, %rcx
; CHECK-NEXT:    movq %r14, %rdx
; CHECK-NEXT:    movq %r13, %rsi
; CHECK-NEXT:    movq %r12, %rdi
; CHECK-NEXT:    callq preserve_most_callee_4args@PLT
; CHECK-NEXT:    addq %r9, %rbx
; CHECK-NEXT:    addq %r8, %r10
; CHECK-NEXT:    addq %rbx, %r10
; CHECK-NEXT:    addq %r10, %rax
; CHECK-NEXT:    popq %rcx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq $8
    i64 %a1, i64 %a2, i64 %a3, i64 %a4, i64 %a5, i64 %a6, i64 %a7, i64 %a8) {
entry:
  %val = call preserve_mostcc i64 @preserve_most_callee_4args(i64 %a1, i64 %a2, i64 %a3, i64 %a4)
  %s1 = add i64 %a5, %a6
  %s2 = add i64 %s1, %a7
  %s3 = add i64 %s2, %a8
  %res = add i64 %s3, %val
  ret i64 %res
}

; Test 3: Over budget (total 14 args) with expected spill.
; Caller has 10 args, Callee has 4 args.
; We expect 1 spill because we exceed the 12-register budget.
define tail_chaincc i64 @tail_chain_caller_extreme(
; CHECK-LABEL: tail_chain_caller_extreme:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    subq $16, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    .cfi_offset %rbp, -16
; CHECK-NEXT:    movq %rsi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movq %rdx, %rbx
; CHECK-NEXT:    movq %rcx, %rbp
; CHECK-NEXT:    movq %r11, %r10
; CHECK-NEXT:    movq %r15, %rcx
; CHECK-NEXT:    movq %r14, %rdx
; CHECK-NEXT:    movq %r13, %rsi
; CHECK-NEXT:    movq %r12, %rdi
; CHECK-NEXT:    callq preserve_most_callee_4args@PLT
; CHECK-NEXT:    addq %r9, %r10
; CHECK-NEXT:    addq %r8, %rbp
; CHECK-NEXT:    addq %r10, %rbp
; CHECK-NEXT:    addq {{[-0-9]+}}(%r{{[sb]}}p), %rbx # 8-byte Folded Reload
; CHECK-NEXT:    addq %rbx, %rax
; CHECK-NEXT:    addq %rbp, %rax
; CHECK-NEXT:    addq $16, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq $8
    i64 %a1, i64 %a2, i64 %a3, i64 %a4, i64 %a5, i64 %a6, i64 %a7, i64 %a8, i64 %a9, i64 %a10) {
entry:
  %val = call preserve_mostcc i64 @preserve_most_callee_4args(i64 %a1, i64 %a2, i64 %a3, i64 %a4)
  %s1 = add i64 %a5, %a6
  %s2 = add i64 %s1, %a7
  %s3 = add i64 %s2, %a8
  %s4 = add i64 %s3, %a9
  %s5 = add i64 %s4, %a10
  %res = add i64 %s5, %val
  ret i64 %res
}
